### ISSUE TITLE
Unable to add/edit comment in `add_layer3_vlan_interface`

### ISSUE THREAD

**Issue by stdedos** [gabstopper/smc-python#35] opened 2018-09-20 15:52 UTC
On an existing Master Engine, with existing Resource and VFW, I am running:

```python
master_engine.physical_interface.add_layer3_vlan_interface(
                        master_if_id, vlan_id,
                        virtual_mapping=vfw_if_id,
                        virtual_resource_name=vfw_resource,
                        comment='{:s}: {:s}'.format(vfw_name, comment))
```

However, result is not coming:
![image](https://user-images.githubusercontent.com/133706/45830647-4af7b000-bd06-11e8-9f80-623a1466dc17.png)

(_I think it happened on creation also; currently it is "definitely" an update_)

**Comment by gabstopper** [comment] 2018-09-30 21:27
Apologize for the delay. 
If the interface existed with the VLAN, then this is by design. I think that is what is happening here. Meaning you already created the interface and VLAN, and your trying to change the comment.

Interface creation supports adding comments during creation (and works):
```
engine = MasterEngine.create(name='virtualfw', master_type='firewall', mgmt_ip='1.1.1.1', mgmt_network='1.1.1.0/24')
engine.virtual_resource.create(name='ve-1', vfw_id=1, comment='my resource comment')
engine.physical_interface.add_layer3_vlan_interface(
    virtual_mapping=1,
    virtual_resource_name='ve-1',
    interface_id=2, vlan_id=2, comment='my interface comment')
```
![image](https://user-images.githubusercontent.com/14811349/46262888-84ca7280-c4cd-11e8-84d5-4f649dd87e4f.png)

If you already have the interface and VLAN, you will not use the same add_layer3_vlan_interface constructor (that's used when you want to add a VLAN to an existing physical interface), instead you can just modify the interface directly:

```
engine = Engine('virtualfw')
interface = engine.interface.get('2.2')
interface.comment = 'I changed the comment'
interface.update()
```
![image](https://user-images.githubusercontent.com/14811349/46262909-be9b7900-c4cd-11e8-9cda-64e7a02c69b1.png)

**Comment by gabstopper** [comment] 2018-10-18 14:04
Closing per clarification and example above

**Closed by gabstopper** 2018-10-18 14:04 UTC
Labels: question
